[package]
name = "pcap-repro"
version = "0.1.0"
authors = ["Julia Evans <julia@jvns.ca>"]
edition = "2018"

[dependencies]
pcap = {version = "0.8.1", features=["capture-stream"]}
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
